// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Trawl",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Trawl",
            targets: ["AppModule"],
            bundleIdentifier: "com.Eric.Trawl",
            teamIdentifier: "VGKCD7Q8NW",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .sparkle),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.userSelectedFiles, mode: .readOnly),
                .fileAccess(.downloadsFolder, mode: .readOnly),
                .fileAccess(.musicFolder, mode: .readOnly),
                .fileAccess(.pictureFolder, mode: .readOnly)
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
	    resources: [
		.process("Resources")
		]
        )
    ]
)
